start-player: 1
border-radius: 5000.0
countdown-sec: 60
debug: true
wait: 1800
start-info:
  - " "
  - "&f======================================================="
  - " "
  - "            &b&l欢迎来到 &4&l死亡互换"
  - " "
  - " &f» &b在这个玩法中，每过一定的时间将会对场上的所有玩家进行随机位置调换！"
  - " &f» &b你需要使用你能想到的一切方法置对手于死地！ 当然，你也可能和自己互换位置。"
  - " &f» &b保护好自己，干爆对手，获得游戏胜利吧！"
  - " "
  - " &4注意： &cPVP 是禁用的 为了方便其他玩家的体验，请勿和平占房间。"
  - " "
  - " &e你正在游玩&bMhxj&f.&aClub"
  - "&f======================================================="