name: DeathExchange
author: KazuhaAyato
main: com.kazuha.de.main
softdepend: [PlaceholderAPI]
version: 1.2.2-BETA4
commands:
  de:
    aliases:
      - deathexchange
      - death
    usage: what the fuck
    description: main command
